# @formatter:off
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hivemq-ce-helm.fullname" . }}
  labels:
{{ include "hivemq-ce-helm.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: hivemq-mqtt
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "hivemq-ce-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
